# Generated by Django 3.1 on 2021-07-01 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('processing', 'Processing'), ('packed', 'Packed'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='processing', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.address')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('processing', 'Processing'), ('packed', 'Packed'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='processing', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.address')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('cart', models.ManyToManyField(to='cart.Cart')),
            ],
        ),
    ]
