# Generated by Django 3.1 on 2021-08-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_productcheckout_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcheckout',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
